name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
                  cache-dependency-path: package-lock.json
            - run: npm install
            - run: npm run test
            - uses: codacy/codacy-coverage-reporter-action@v1
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                coverage-reports: coverage/lcov.info
