name: CI

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
                  cache-dependency-path: package-lock.json
            - run: npm install
