name: Release

on:
  push:
    tags:
      - "*"

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - id: json2dir
        uses: jsmith/changes-since-last-tag@v0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      TAG: ${{ steps.get_tag.outputs.TAG }}
      JSON2DIR: ${{ steps.json2dir.outputs.any_changed }}

  json2dir:
    runs-on: ubuntu-latest
    needs: prepare
#     if: needs.prepare.outputs.JSON2DIR == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16'
            cache: 'npm'
            cache-dependency-path: package-lock.json
      - run: npm ci
      - run: sed -i 's/1.0.0/${{ needs.prepare.outputs.TAG }}/g' package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
